### ISSUE TITLE
Set up of Kanban Board

### ISSUE THREAD

**Issue by JohnFTitor** [carloshs1994/choose-your-pokemon#21]
# Hello 👋🏻 

Here's the link to our Github project: 

https://github.com/carloshs1994/choose-your-pokemon/projects/1

There are two people in this team project.

Cheers!

<img src="https://media1.giphy.com/media/xIhGpmuVtuEpi/giphy.gif"/>

**Comment by carloshs1994** [comment]
<img src="https://media3.giphy.com/media/slVWEctHZKvWU/giphy.gif"/>

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @carloshs1994 & @JohnFTitor, 

Good job on implementing all the requirements. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
