### ISSUE TITLE
Comment counter function fix

### ISSUE THREAD

**Issue by Yothu** [carloshs1994/choose-your-pokemon#34]
Excellent and beautiful project guys! I only have one minor issue.

### Issue

https://github.com/carloshs1994/choose-your-pokemon/blob/7ffcf1d5bb1ff194b3399b715fceb6ad032000b6/src/scripts/modules/comments.js#L23-L26

The name of the `commentCounter` function does **do not reflect its functionality**, because it gets from the very beginning the value that it is supposed to return, in this case, the **length of the comment array**. What it is actually doing is **checking that the length of the comment array is valid**. 

### Suggestion

To fix this issue I would recommend that in the `commentCounter` function put as a **parameter the array of comments**, and then **return the length of the array**.

**Comment by JohnFTitor** [comment]
Hi @Yothu 

Thanks for your review. We're going to fix it right away!

<img src="https://media1.giphy.com/media/xuXzcHMkuwvf2/giphy.gif"/>
